name: Workflow to print a message
on:
  push:
    paths:
      - "../../components/web/**"
jobs:
  printer-job:
    runs-on: ubuntu-latest
    steps:
      - name: print a message
        run: echo "This is a test workflow"
